
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cikaandhini
 */
public class setor extends javax.swing.JFrame {

    /**
     * Creates new form setor
     */
    public setor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSETORUANG = new javax.swing.JTextField();
        buttonSETOR = new javax.swing.JButton();
        buttonBACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon("R:\\DOWNLOAD\\Logo Bank BNI PNG.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 10, 200, 60);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 19)); // NOI18N
        jLabel2.setText("ANJUNGAN TUNAI MANDIRI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 80, 260, 30);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setText("BNI SYARIAH - YOGYAKARTA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 110, 290, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel1.setText("Setor Tunai ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 140, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah uang :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 220, 100, 30);

        txtSETORUANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSETORUANGActionPerformed(evt);
            }
        });
        jPanel1.add(txtSETORUANG);
        txtSETORUANG.setBounds(150, 220, 230, 30);

        buttonSETOR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonSETOR.setText("SETOR");
        buttonSETOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSETORActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSETOR);
        buttonSETOR.setBounds(160, 290, 120, 40);

        buttonBACK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonBACK.setText("KEMBALI");
        buttonBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBACKActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBACK);
        buttonBACK.setBounds(160, 350, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 460);

        setBounds(0, 0, 461, 447);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSETORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSETORActionPerformed
        String setoran = txtSETORUANG.getText();
            int jmlsetor = Integer.parseInt(setoran);
            int saldo = 1000000;
            int saldoakhir = saldo+jmlsetor;
            
        if (jmlsetor%100!=0) {
            JOptionPane.showMessageDialog(null, "Mesin ATM BNI tidak menerima uang koin \nSilahkan ulangi kembali!", "Transaksi Gagal", 0);
        } else if (jmlsetor<=50000) {
            JOptionPane.showMessageDialog(null, "Besaran minimal setor tunai adalah Rp 50.000,00", "ERROR", 0);
        }else if (jmlsetor>=50000) {
            JOptionPane.showMessageDialog(null, "Terima kasih telah melakukan penyetoran uang. Jumlah saldo terakhir adalah " + saldoakhir);
        }
        
    }//GEN-LAST:event_buttonSETORActionPerformed

    private void buttonBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBACKActionPerformed
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_buttonBACKActionPerformed

    private void txtSETORUANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSETORUANGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSETORUANGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBACK;
    private javax.swing.JButton buttonSETOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSETORUANG;
    // End of variables declaration//GEN-END:variables
}
