
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cikaandhini
 */
public class tarik extends javax.swing.JFrame {


    public tarik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTARIKUANG = new javax.swing.JTextField();
        buttonTARIK = new javax.swing.JButton();
        buttonBACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon("R:\\DOWNLOAD\\Logo Bank BNI PNG.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 10, 200, 60);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 19)); // NOI18N
        jLabel2.setText("ANJUNGAN TUNAI MANDIRI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 80, 260, 30);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setText("BNI SYARIAH - YOGYAKARTA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 110, 290, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel1.setText("Tarik Tunai ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 140, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah uang :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 220, 100, 30);

        txtTARIKUANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTARIKUANGActionPerformed(evt);
            }
        });
        jPanel1.add(txtTARIKUANG);
        txtTARIKUANG.setBounds(150, 220, 230, 30);

        buttonTARIK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonTARIK.setText("TARIK");
        buttonTARIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTARIKActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTARIK);
        buttonTARIK.setBounds(150, 290, 120, 40);

        buttonBACK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonBACK.setText("KEMBALI");
        buttonBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBACKActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBACK);
        buttonBACK.setBounds(150, 350, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 450);

        setBounds(0, 0, 435, 457);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBACKActionPerformed
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_buttonBACKActionPerformed

    private void buttonTARIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTARIKActionPerformed
        String tarikan = txtTARIKUANG.getText();
            int saldo = 1000000;
            int jmltarik = Integer.parseInt(tarikan);
            int saldoakhir = saldo-jmltarik;
        if (jmltarik%100!=0) {
            JOptionPane.showMessageDialog(null, "Mesin ATM BNI tidak menerima penarikan berupa uang koin \nSilahkan ulangi lagi", "Transaksi Gagal", 0);
        }else if (jmltarik<=saldo) {
            JOptionPane.showMessageDialog(null, "Saldo anda tidak mencukupi \nSilahkan lakukan penyetoran", "Transaksi Gagal", 0);
        }else if (jmltarik<50000) {
            JOptionPane.showMessageDialog(null, "Besaran minimal penyetoran tunai adalah Rp 50.000,00 ","Transaksi Gagal",0);
        }else{
            JOptionPane.showMessageDialog(null, "Terima kasih telah melakukan penarikan uang. Jumlah saldo terakhir adalah " + saldoakhir);
            if (saldoakhir<=50000) {
                JOptionPane.showMessageDialog(null, "Saldo minimal Rp 50.000,00 Segera lakukan penyetoran untuk menghindari penutupan akun.","CAUTION",2);
            }
        }
        
    }//GEN-LAST:event_buttonTARIKActionPerformed

    private void txtTARIKUANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTARIKUANGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTARIKUANGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tarik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBACK;
    private javax.swing.JButton buttonTARIK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTARIKUANG;
    // End of variables declaration//GEN-END:variables
}
